name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python requirements
        run: |
          python -m venv env
          . env/bin/activate
          pip install -U pip
          pip install -r requirements.txt
          echo "$PWD/venv/bin" >> $GITHUB_PATH

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Run pipeline
        run: just all
